"""add document_sequences

Revision ID: 4eeb22978a15
Revises: e2b6594c7d63
Create Date: 2026-09-30 22:20:23.996279

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4eeb22978a15"
down_revision: str | None = "e2b6594c7d63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_sequences",
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "last_value >= 0", name=op.f("ck_document_sequences_last_value_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_sequences")),
        sa.UniqueConstraint("kind", "year", name=op.f("uq_document_sequences_kind")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_sequences")
    # ### end Alembic commands ###
