"""add invoices

Revision ID: 53682f83126a
Revises: 7a00822dbd07
Create Date: 2026-10-03 16:14:10.210824

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "53682f83126a"
down_revision: str | None = "7a00822dbd07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_paid >= 0 AND amount_paid <= total",
            name=op.f("ck_invoices_amount_paid_in_range"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_invoices_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_invoices_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_invoices_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_invoices_owner_id_users")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_invoices_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_invoices_number")),
        sa.UniqueConstraint("order_id", name=op.f("uq_invoices_order_id")),
    )
    op.create_index(op.f("ix_invoices_account_id"), "invoices", ["account_id"], unique=False)
    op.create_index(op.f("ix_invoices_owner_id"), "invoices", ["owner_id"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(op.f("ix_invoices_team_id"), "invoices", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_team_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_owner_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_account_id"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
