"""add activities

Revision ID: 6f4cec599c30
Revises: f8538da4d43b
Create Date: 2026-10-03 16:00:55.962705

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6f4cec599c30"
down_revision: str | None = "f8538da4d43b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("created_by_kind", sa.String(length=20), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('account', 'contact', 'lead', 'opportunity')",
            name=op.f("ck_activities_entity_type"),
        ),
        sa.CheckConstraint(
            "type IN ('call', 'email', 'meeting', 'note', 'chat', 'whatsapp')",
            name=op.f("ck_activities_type"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_activities_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_activities_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        "ix_activities_entity_timeline",
        "activities",
        ["entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_activities_owner_id"), "activities", ["owner_id"], unique=False)
    op.create_index(op.f("ix_activities_team_id"), "activities", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_team_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_owner_id"), table_name="activities")
    op.drop_index("ix_activities_entity_timeline", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
