"""add products

Revision ID: 9264b1054f5f
Revises: d60a4933ac27
Create Date: 2026-09-30 22:41:30.198240

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9264b1054f5f"
down_revision: str | None = "d60a4933ac27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("tax_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("stock_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reserved_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("reorder_level", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("min_order_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_products_lead_time_days_non_negative")
        ),
        sa.CheckConstraint("min_order_qty > 0", name=op.f("ck_products_min_order_qty_positive")),
        sa.CheckConstraint(
            "reorder_level >= 0", name=op.f("ck_products_reorder_level_non_negative")
        ),
        sa.CheckConstraint(
            "reserved_qty <= stock_qty", name=op.f("ck_products_reserved_within_stock")
        ),
        sa.CheckConstraint("reserved_qty >= 0", name=op.f("ck_products_reserved_qty_non_negative")),
        sa.CheckConstraint("stock_qty >= 0", name=op.f("ck_products_stock_qty_non_negative")),
        sa.CheckConstraint(
            "tax_pct >= 0 AND tax_pct <= 100", name=op.f("ck_products_tax_pct_range")
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_products_unit_price_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
