"""add quotations

Revision ID: f9e618d44197
Revises: e08daf18e828
Create Date: 2026-10-03 16:14:01.986146

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f9e618d44197"
down_revision: str | None = "e08daf18e828"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotations",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("terms", sa.Text(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("created_by_kind", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total >= 0", name=op.f("ck_quotations_total_non_negative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_quotations_version_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_quotations_account_id_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_quotations_opportunity_id_opportunities"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_quotations_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_quotations_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotations")),
        sa.UniqueConstraint("number", "version", name=op.f("uq_quotations_number")),
    )
    op.create_index(op.f("ix_quotations_account_id"), "quotations", ["account_id"], unique=False)
    op.create_index(op.f("ix_quotations_number"), "quotations", ["number"], unique=False)
    op.create_index(
        op.f("ix_quotations_opportunity_id"), "quotations", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_quotations_owner_id"), "quotations", ["owner_id"], unique=False)
    op.create_index(op.f("ix_quotations_status"), "quotations", ["status"], unique=False)
    op.create_index(op.f("ix_quotations_team_id"), "quotations", ["team_id"], unique=False)
    op.create_table(
        "quotation_items",
        sa.Column("quotation_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "discount_pct >= 0 AND discount_pct <= 100",
            name=op.f("ck_quotation_items_discount_range"),
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_quotation_items_qty_positive")),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_quotation_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_quotation_items_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_items_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_items")),
    )
    op.create_index(
        op.f("ix_quotation_items_product_id"), "quotation_items", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_items_quotation_id"), "quotation_items", ["quotation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quotation_items_quotation_id"), table_name="quotation_items")
    op.drop_index(op.f("ix_quotation_items_product_id"), table_name="quotation_items")
    op.drop_table("quotation_items")
    op.drop_index(op.f("ix_quotations_team_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_status"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_owner_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_opportunity_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_number"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_account_id"), table_name="quotations")
    op.drop_table("quotations")
    # ### end Alembic commands ###
